server:
  port: 80

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB Source
    url: jdbc:mysql://springboot-db.c5hxzzygkuri.ap-northeast-2.rds.amazonaws.com:3306/myblog?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    # DB username
    username: admin
    # DB password
    password: kp23156385
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug